Repository cedarcode/webauthn-ruby, pull requests merged in 2020-06, with the labels that each got.

#318 docs: fix typo in README.md
  README.md
Labels: type: docs

#314 fix: AttestationStatement::TPM#valid? blowing up when using libssl 1.0.2
  .travis.yml
  script/ci/install-openssl
  script/ci/install-ruby
  spec/conformance/Gemfile.lock
  webauthn.gemspec
Labels: area: tpm attestation

#313 Remove SignatureVerifier
  lib/webauthn/attestation_statement/android_key.rb
  lib/webauthn/attestation_statement/base.rb
  lib/webauthn/attestation_statement/fido_u2f.rb
  lib/webauthn/attestation_statement/packed.rb
  lib/webauthn/attestation_statement/tpm.rb
  lib/webauthn/authenticator_assertion_response.rb
  lib/webauthn/public_key.rb
  lib/webauthn/signature_verifier.rb
  spec/webauthn/public_key_spec.rb
  spec/webauthn/signature_verifier_spec.rb
Labels: type: refactor

#326 refactor: remove `icon` from `user` in public key options
  lib/webauthn/public_key_credential/entity.rb
  spec/webauthn/public_key_credential/creation_options_spec.rb
Labels: type: refactor
